"""Generate the Section 6.1 table from checked results."""
import json
from pathlib import Path
OUT=Path(__file__).resolve().parent

def sci(x):
    a,b=f'{x:.2e}'.split('e')
    return a+r'\times10^{'+str(int(b))+'}'

def render(rows):
    table=r'''% Generated by render_expcompare.py.
\begin{table}[tb]
\caption{Observed errors and upper bounds for the linearized error at $t=100$.
The split bound includes both the strict-upper and diagonal contributions.
The last column measures the full matrix linearization residual.}
\label{tab:backwardcomparison}
\centering\scriptsize
\setlength{\tabcolsep}{3pt}
\begin{tabular}{llrrrrr}
$X$ & method & $f$ & $p_{\rm split}$ & $p_{\bfrak}$ & $p_{\rm full}$ & $r_{\rm lin}$ \\
\hline
'''
    for r in rows:
        if r['t']!=100: continue
        label='$S_8$' if r['family']=='S8' else '$P_{12}$'
        table+=label+' & '+r['method']+' & '+' & '.join('$'+sci(r[k])+'$' for k in
             ['forward','p_split','p_b','p_full','relative_linearization_residual'])+r' \\'+'\n'
    table+=r'\end{tabular}'+'\n'+r'\end{table}'+'\n'
    (OUT/'expcompare_table.tex').write_text(table)

if __name__=='__main__': render(json.loads((OUT/'expcompare_results.json').read_text())['results'])
