"""Reproduce Table 6.2 and check its derivative matrices independently.

Run with Python 3, NumPy, and SciPy: python3 reproduce_table.py
The generated regimes_table.tex is written beside this script.
Only the strictly upper-triangular standard shift is used here. Its exact
nilpotency index is its dimension, so no numerical rank decision is needed.
The finite derivative series is compared with scipy.linalg.expm_frechet,
which implements the scaling-and-squaring algorithm of Al-Mohy and Higham.
"""

from math import factorial
from pathlib import Path

import numpy as np
import scipy
from scipy.linalg import expm, expm_frechet, svdvals


def derivative_matrix(a, pairs):
    """Finite-series derivative on a Frobenius-orthonormal unit basis."""
    d = a.shape[0]
    powers = [np.eye(d)]
    for _ in range(1, d):
        powers.append(powers[-1] @ a)
    columns = []
    reference = []
    for i, j in pairs:
        e = np.zeros_like(a)
        e[i, j] = 1.0
        value = np.zeros_like(a)
        for p in range(d):
            for q in range(d):
                value += (powers[p] @ e @ powers[q]) / factorial(p + q + 1)
        columns.append(value.ravel(order="F"))
        reference.append(expm_frechet(a, e, compute_expm=False).ravel(order="F"))
    matrix = np.column_stack(columns)
    independent = np.column_stack(reference)
    error = np.linalg.norm(matrix - independent) / np.linalg.norm(matrix)
    if error > 1e-11:
        raise AssertionError(f"Independent derivative check failed: {error}")
    return matrix, error


def conditions(d, t):
    s = np.diag(np.ones(d - 1), 1)
    a = t * s
    exponential = sum(
        (np.linalg.matrix_power(a, k) / factorial(k) for k in range(d)),
        np.zeros_like(a),
    )
    np.testing.assert_allclose(exponential, expm(a), rtol=1e-12, atol=1e-12)
    factor = np.linalg.norm(a, "fro") / np.linalg.norm(exponential, "fro")
    values = []
    errors = []
    for condition in (lambda i, j: i < j,
                      lambda i, j: i <= j,
                      lambda i, j: True):
        pairs = [(i, j) for i in range(d) for j in range(d)
                 if condition(i, j)]
        matrix, error = derivative_matrix(a, pairs)
        values.append(factor * svdvals(matrix)[0])
        errors.append(error)
    return values, max(errors)


def main():
    rows = []
    maximum_error = 0.0
    for d in (3, 4):
        for t in (1, 10, 100):
            values, error = conditions(d, t)
            maximum_error = max(maximum_error, error)
            print(f"d={d}, t={t:3}: " + ", ".join(f"{v:.10g}" for v in values))
            rows.append(f" {d} & {t} & "
                        + " & ".join(f"{v:.5f}" for v in values) + r" \\")

    # Independently check the finite-t example in Section 5.1.
    a = 5 * np.diag(np.ones(2), 1)
    strict, _ = derivative_matrix(a, [(0, 1), (0, 2), (1, 2)])
    full, _ = derivative_matrix(a, [(i, j) for i in range(3) for j in range(3)])
    exact = 0.5 * np.sqrt(29 + 5 * np.sqrt(33))
    np.testing.assert_allclose(svdvals(strict)[0], exact, rtol=1e-14)
    print(f"Section 5.1 absolute norms: {exact:.10f}, {svdvals(full)[0]:.10f}")
    print(f"Largest relative derivative-matrix discrepancy: {maximum_error:.3e}")
    print(f"NumPy {np.__version__}; SciPy {scipy.__version__}")

    table = r"""% Generated by reproduce_table.py. Values rounded to five decimals.
\begin{table}[tb]
\caption{Relative Frobenius condition numbers of $\exp$ at $tS$ for three
perturbation classes, computed from the finite derivative expansion.}
\label{tab:regimes}
\centering
\begin{tabular}{rr|rrr}
 $d$ & $t$ & $\kappa_{\nfrak(d)}(tS)$ & $\kappa_{\bfrak(d)}(tS)$
 & $\kappa_{\mathrm{full}}(tS)$ \\
\hline
""" + "\n".join(rows) + r"""
\end{tabular}
\end{table}
"""
    Path(__file__).with_name("regimes_table.tex").write_text(table)


if __name__ == "__main__":
    main()
