"""Verify Proposition 4.3 and generate its finite-scale comparison table.

Uses the finite derivative series, independent SciPy Frechet evaluations,
and 80-digit block exponentials for the nine published d=4 cases.
Run from any directory; generated files are placed beside this script.
"""
import json
from math import factorial, sqrt
from pathlib import Path
import numpy as np
import scipy
from scipy.linalg import expm_frechet, svdvals
import mpmath as mp


def evaluate(d, j, delta, t, independent=False):
    x = np.diag(np.ones(d-1), 1)
    x[j-1, j] = delta
    powers = [np.eye(d)]
    for k in range(1, d):
        powers.append(powers[-1] @ x)
    coeff = []
    pairs = [(i,k) for i in range(d) for k in range(i+1,d)]
    for n in range(d-1):
        columns = []
        for i,k in pairs:
            e = np.zeros((d,d)); e[i,k] = 1
            columns.append(sum((powers[p] @ e @ powers[n-p]
                                for p in range(n+1)),np.zeros((d,d))).ravel()
                           / factorial(n+1))
        coeff.append(np.column_stack(columns))
    top = np.zeros_like(coeff[-1])
    for col,(i,k) in enumerate(pairs):
        if k == i+1:
            top[d-1,col] = (1 if i==j-1 else delta)/factorial(d-1)
    np.testing.assert_allclose(coeff[-1],top,rtol=2e-14,atol=1e-18)
    # Scale out the largest power before summation and the SVD.
    derivative = sum((t**(n-d+2)*c for n,c in enumerate(coeff)),np.zeros_like(top))
    exponential = sum((t**(k-d+1)*p/factorial(k) for k,p in enumerate(powers)),np.zeros_like(x))
    kappa = np.linalg.norm(x)*svdvals(derivative)[0]/np.linalg.norm(exponential)
    m,s = max(j,d-j),min(j,d-j)
    h = 2 if j==d-j else 1
    bscale = h*(factorial(d-1)/factorial(m-1))**2
    amplitude = sqrt((d-2+delta**2)*(1+(d-2)*delta**2))
    q = amplitude/sqrt(delta**2+bscale*t**(-2*s))
    n = [max(j-k,0)+max(d-j-k,0) for k in range(d)]
    c = [d-k-n[k] for k in range(d)]
    denominator = sum((n[k]+delta**2*c[k])*t**(2*(k-d+1))/factorial(k)**2 for k in range(d))
    np.testing.assert_allclose(np.linalg.norm(exponential)**2,denominator,rtol=2e-14)
    a = factorial(d-1)*sum(t**(k-d+2)/factorial(k) for k in range(d-2))
    b = factorial(m-1)**2/h*sum(n[k]/factorial(k)**2 for k in range(m-1))
    b += factorial(d-1)**2*sum(c[k]/factorial(k)**2 for k in range(1,d-1))
    error,bound = abs(kappa/q-1),a+b/(2*t*t)
    assert error <= bound + 1e-12,(d,j,delta,t,error,bound)
    independent_error = 0.
    if independent:
        columns=[]
        for i,k in pairs:
            e=np.zeros_like(x);e[i,k]=1
            columns.append(expm_frechet(t*x,e,compute_expm=False).ravel()/t**(d-2))
        reference=np.column_stack(columns)
        independent_error=np.linalg.norm(reference-derivative)/np.linalg.norm(derivative)
        assert independent_error<2e-10,independent_error
    return kappa,q,bound,independent_error


def high_precision(delta,t):
    mp.mp.dps=80
    d=4; x=mp.zeros(d)
    for i in range(d-1):x[i,i+1]=1
    x[1,2]=mp.mpf(delta)
    a=mp.mpf(t)*x
    columns=[]
    for i in range(d):
        for j in range(i+1,d):
            z=mp.zeros(2*d)
            for r in range(d):
                for c in range(d):z[r,c]=z[r+d,c+d]=a[r,c]
            z[i,j+d]=1
            y=mp.expm(z)
            columns.append([y[r,c+d] for r in range(d) for c in range(d)])
    mat=mp.matrix([[col[r] for col in columns] for r in range(d*d)])
    singular=mp.svd(mat,compute_uv=False)[0]
    return float(mp.norm(a)*singular/mp.norm(mp.expm(a)))


def main():
    cases=0; independent_max=0.
    for d in range(3,9):
        for j in range(1,d):
            for delta in (0.,1e-6,.01,.5,1.):
                for t in (1.,10.,100.,1000.):
                    result=evaluate(d,j,delta,t,independent=(t<=100 and delta in (0.,.01,1.)))
                    independent_max=max(independent_max,result[3]);cases+=1
    rows=[];tex=[];hpmax=0.
    for delta in (1e-2,1e-4,1e-6):
        B=72.; tau=(sqrt(B)/delta)**.5
        K=sqrt((2+delta**2)*(1+2*delta**2))/delta
        ratios=[]
        for u in (.1,1.,10.):
            t=u*tau
            k,q,bound,_=evaluate(4,2,delta,t)
            hp=high_precision(delta,t)
            hpmax=max(hpmax,abs(k/hp-1))
            assert abs(k/hp-1)<1e-12
            rows.append(dict(delta=delta,u=u,t=t,tau=tau,kappa=k,Q=q,
                             kappa_over_Q=k/q,kappa_over_K=k/K,bound=bound,
                             high_precision_kappa=hp))
            ratios.append(k/q)
        tex.append(f" $10^{{{int(round(np.log10(delta)))}}}$ & {tau:.2f} & "+" & ".join(f"{r:.6f}" for r in ratios)+r" \\")
    table=r"""% Generated by reproduce_weak_link.py.
\begin{table}[h!]
\caption{One weak link, $d=4$, $j=2$: ratios $\kappa(tX_\delta)/Q_\delta(t)$
at three multiples of $\tau_\delta$. The ratios approach one as the
transition moves to larger $t$.}
\label{tab:weaklink}
\centering
\begin{tabular}{rrrrr}
$\delta$ & $\tau_\delta$ & $t=0.1\tau_\delta$ & $t=\tau_\delta$ & $t=10\tau_\delta$\\
\hline
"""+"\n".join(tex)+r"""
\end{tabular}
\end{table}
"""
    root=Path(__file__).resolve().parent
    (root/'weak_link_table.tex').write_text(table)
    data=dict(verification_cases=cases,scipy_max_relative_discrepancy=independent_max,
              high_precision_max_relative_discrepancy=hpmax,rows=rows,
              versions=dict(numpy=np.__version__,scipy=scipy.__version__,mpmath=mp.__version__))
    (root/'weak_link_results.json').write_text(json.dumps(data,indent=2)+'\n')
    print(json.dumps({k:v for k,v in data.items() if k!='rows'},indent=2))
    print(table)


if __name__=='__main__':main()
