"""Reproduce the superdiagonal diagnostic for the stored S8 output.

The default input is the hexadecimal binary64 output stored in
``expcompare_results.json``.  The logarithm, exponential, and Frechet
derivative actions are evaluated with mpmath at 100 decimal digits.
"""

import json
from pathlib import Path

import mpmath as mp
import numpy as np


ROOT = Path(__file__).resolve().parent


def frobenius_norm(matrix):
    return mp.sqrt(sum(abs(entry) ** 2 for entry in matrix))


def decode_matrix(rows):
    return np.array([[float.fromhex(entry) for entry in row] for row in rows])


def recorded_case(path, method):
    payload = json.loads(path.read_text())
    return next(
        row
        for row in payload["computed_matrices"]
        if row["family"] == "S8"
        and row["t"] == 100
        and row["method"] == method
    )


def derivative_action(powers, direction):
    dimension = direction.rows
    result = mp.zeros(dimension)
    for left in range(dimension):
        for right in range(dimension):
            result += (
                powers[left]
                * direction
                * powers[right]
                / mp.factorial(left + right + 1)
            )
    return result


def band_condition_number(powers, scale, offset):
    dimension = powers[0].rows
    columns = []
    for row in range(dimension - offset):
        unit = mp.zeros(dimension)
        unit[row, row + offset] = 1
        image = derivative_action(powers, unit)
        columns.append([float(entry) for entry in image])
    matrix = np.column_stack(columns)
    return float(scale) * np.linalg.svd(matrix, compute_uv=False)[0]


def analyse(input_path, method):
    case = recorded_case(input_path, method)
    array_a = decode_matrix(case["A_hex"])
    array_y = decode_matrix(case["Y_hex"])

    with mp.workdps(100):
        a = mp.matrix(array_a.tolist())
        y = mp.matrix(array_y.tolist())
        dimension = a.rows
        exponential = mp.expm(a)
        backward_error = mp.logm(y) - a
        norm_a = frobenius_norm(a)
        norm_exponential = frobenius_norm(exponential)
        powers = [mp.eye(dimension)]
        for _ in range(1, dimension):
            powers.append(powers[-1] * a)
        scale = norm_a / norm_exponential

        rows = []
        images = []
        for offset in range(1, dimension):
            band = mp.zeros(dimension)
            for row in range(dimension - offset):
                band[row, row + offset] = backward_error[row, row + offset]
            image = derivative_action(powers, band)
            delta = frobenius_norm(band) / norm_a
            effect = frobenius_norm(image) / norm_exponential
            rows.append(
                {
                    "nu": offset,
                    "delta": float(delta),
                    "effect": float(effect),
                    "gain": float(effect / delta) if delta else None,
                    "condition_number": band_condition_number(
                        powers, scale, offset
                    ),
                }
            )
            images.append(image)

        strict_error = mp.zeros(dimension)
        for offset in range(1, dimension):
            for row in range(dimension - offset):
                strict_error[row, row + offset] = backward_error[
                    row, row + offset
                ]
        image_sum = mp.zeros(dimension)
        for image in images:
            image_sum += image
        summary = {
            "family": "S8",
            "t": 100,
            "method": method,
            "precision_digits": 100,
            "rows": rows,
            "strict_upper_backward": float(
                frobenius_norm(strict_error) / norm_a
            ),
            "sum_band_effects": float(
                sum(frobenius_norm(image) for image in images)
                / norm_exponential
            ),
            "combined_band_effect": float(
                frobenius_norm(image_sum) / norm_exponential
            ),
        }
    return summary


def scientific(value):
    coefficient, exponent = f"{value:.2e}".split("e")
    return rf"${coefficient}\times10^{{{int(exponent)}}}$"


def write_table(summary, path):
    body = []
    for row in summary["rows"]:
        gain = f"${row['gain']:.2f}$" if row["gain"] >= 0.1 else scientific(row["gain"])
        condition = (
            f"${row['condition_number']:.2f}$"
            if row["condition_number"] >= 0.1
            else scientific(row["condition_number"])
        )
        body.append(
            f"{row['nu']} & {scientific(row['delta'])} & "
            f"{scientific(row['effect'])} & {gain} & {condition}\\\\"
        )
    text = "\n".join(
        [
            "% Generated by superdiag_decomp.py from the stored binary64 output.",
            r"\begin{table}[tb]",
            r"\caption{Bandwise diagnostic for the recorded \texttt{expm} output at",
            r"$A=100S_8$. The quantities $\delta_\nu$ and $q_\nu$ use the recorded",
            r"backward error; $\kappa_{\mathcal B_\nu}(A)$ is computed independently",
            r"from the finite Fr\'echet series.}",
            r"\label{tab:superdiag}",
            r"\centering\small",
            r"\setlength{\tabcolsep}{5pt}",
            r"\begin{tabular}{crrrr}",
            r"$\nu$ & $\delta_\nu$ & $q_\nu$ & $g_\nu$ & $\kappa_{\mathcal B_\nu}(A)$\\",
            r"\hline",
            *body,
            r"\end{tabular}",
            r"\end{table}",
            "",
        ]
    )
    path.write_text(text)


def main():
    summaries = {
        method: analyse(ROOT / "expcompare_results.json", method)
        for method in ("expm", "poly")
    }
    (ROOT / "superdiag_results.json").write_text(
        json.dumps(summaries, indent=2) + "\n"
    )
    write_table(summaries["expm"], ROOT / "superdiag_table.tex")
    print(json.dumps(summaries, indent=2))


if __name__ == "__main__":
    main()
